# Form implementation generated from reading ui file 'H:\Game\Hollow_Knight\App_BP\Code\next.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ask_next(object):
    def setupUi(self, ask_next):
        ask_next.setObjectName("ask_next")
        ask_next.resize(400, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ask_next.sizePolicy().hasHeightForWidth())
        ask_next.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("TsangerYuMo W03")
        ask_next.setFont(font)
        self.yes = QtWidgets.QPushButton(parent=ask_next)
        self.yes.setGeometry(QtCore.QRect(220, 130, 150, 50))
        font = QtGui.QFont()
        font.setFamily("TsangerYuMo W03")
        font.setPointSize(14)
        self.yes.setFont(font)
        self.yes.setObjectName("yes")
        self.no = QtWidgets.QPushButton(parent=ask_next)
        self.no.setGeometry(QtCore.QRect(30, 130, 150, 50))
        font = QtGui.QFont()
        font.setFamily("TsangerYuMo W03")
        font.setPointSize(14)
        self.no.setFont(font)
        self.no.setObjectName("no")
        self.icon_stella = QtWidgets.QLabel(parent=ask_next)
        self.icon_stella.setGeometry(QtCore.QRect(260, 20, 100, 100))
        self.icon_stella.setText("")
        self.icon_stella.setObjectName("icon_stella")
        self.text = QtWidgets.QLabel(parent=ask_next)
        self.text.setGeometry(QtCore.QRect(40, 40, 201, 81))
        font = QtGui.QFont()
        font.setFamily("TsangerYuMo W03")
        font.setPointSize(14)
        self.text.setFont(font)
        self.text.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.text.setWordWrap(True)
        self.text.setObjectName("text")

        self.retranslateUi(ask_next)
        QtCore.QMetaObject.connectSlotsByName(ask_next)

    def retranslateUi(self, ask_next):
        _translate = QtCore.QCoreApplication.translate
        ask_next.setWindowTitle(_translate("ask_next", "开启下一局"))
        self.yes.setText(_translate("ask_next", "开启下一局"))
        self.no.setText(_translate("ask_next", "再想想"))
        self.text.setText(_translate("ask_next", "护符选完啦？               比赛看完啦？               下一局要来咯？"))
