# Form implementation generated from reading ui file 'H:\Game\Hollow_Knight\App_BP\Code\reset.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ask_reset(object):
    def setupUi(self, ask_reset):
        ask_reset.setObjectName("ask_reset")
        ask_reset.resize(400, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ask_reset.sizePolicy().hasHeightForWidth())
        ask_reset.setSizePolicy(sizePolicy)
        self.yes = QtWidgets.QPushButton(parent=ask_reset)
        self.yes.setGeometry(QtCore.QRect(220, 130, 150, 50))
        font = QtGui.QFont()
        font.setFamily("TsangerYuMo W03")
        font.setPointSize(14)
        self.yes.setFont(font)
        self.yes.setObjectName("yes")
        self.no = QtWidgets.QPushButton(parent=ask_reset)
        self.no.setGeometry(QtCore.QRect(30, 130, 150, 50))
        font = QtGui.QFont()
        font.setFamily("TsangerYuMo W03")
        font.setPointSize(14)
        self.no.setFont(font)
        self.no.setObjectName("no")
        self.icon_stella = QtWidgets.QLabel(parent=ask_reset)
        self.icon_stella.setGeometry(QtCore.QRect(260, 20, 100, 100))
        self.icon_stella.setText("")
        self.icon_stella.setObjectName("icon_stella")
        self.text = QtWidgets.QLabel(parent=ask_reset)
        self.text.setGeometry(QtCore.QRect(40, 40, 201, 81))
        font = QtGui.QFont()
        font.setFamily("TsangerYuMo W03")
        font.setPointSize(14)
        self.text.setFont(font)
        self.text.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.text.setWordWrap(True)
        self.text.setObjectName("text")

        self.retranslateUi(ask_reset)
        QtCore.QMetaObject.connectSlotsByName(ask_reset)

    def retranslateUi(self, ask_reset):
        _translate = QtCore.QCoreApplication.translate
        ask_reset.setWindowTitle(_translate("ask_reset", "真的要重置吗"))
        self.yes.setText(_translate("ask_reset", "确认重置"))
        self.no.setText(_translate("ask_reset", "再想想"))
        self.text.setText(_translate("ask_reset", "真的要重置吗？           会全部初始化哟！                           确认了就不能改咯！"))
